name: Update Trophy SVG

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  update-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download SVG
        run: |
          mkdir -p assets
          curl -sL "https://github-profile-trophy-j5llo88zr-aakashs-projects-22fd0f65.vercel.app/?username=aakash232&theme=radical&row=1&column=8&margin-h=15&margin-w=5&no-bg=false&title=-Followers,-Stars,-Issues" -o assets/trophy.svg

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/trophy.svg
          git diff --quiet && echo "No changes to commit" || git commit -m "Update trophy.svg"
          git push
