name: Update Trophy SVG

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    env:
      VERCEL_BYPASS_SECRET: ${{ secrets.VERCEL_TROPHY_BYPASS_SECRET }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Trophy SVG with Bypass Header
        run: |
          mkdir -p assets
          echo "Assets directory contents before download:"
          ls -a assets
          
          curl -sL "https://github-profile-trophy-j5llo88zr-aakashs-projects-22fd0f65.vercel.app/?username=aakash232&theme=radical&row=1&column=8&margin-h=15&margin-w=5&no-bg=false&title=-Followers%2C-Stars%2C-Issues" \
            -H "x-vercel-protection-bypass: $VERCEL_BYPASS_SECRET" \
            -o assets/trophy.svg

          echo "Assets directory contents after download:"
          ls -a assets

      - name: Commit if Changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Check if there are changes before adding and committing
          git diff --quiet || (git add assets/trophy.svg && git commit -m "Update trophy.svg")
          
      - name: Pull & Push Changes
        run: |
          git pull --rebase # Now it will work since we've committed changes
          git push
